name: sync-changes

on:
  push:
    branches:
      - main
    paths:
      - 'github-sync/github-data/sigstore/*.yaml'
      - 'github-sync/Pulumi.github-prod.yaml'

env:
 PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
 GITHUB_OWNER: sigstore

jobs:
  Update:
    name: sync-changes-sigstore
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - uses: sigstore/github-sync@main
      with:
        work_dir: ./github-sync
        config_directory: ./github-sync/github-data
        stack_name: sigstore/github-prod
        pulumi_access_token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        pulumi_command: up
        gh_token: ${{ secrets.GITHUB_TOKEN }}
