name: 'Dependency Review'
on:
  workflow_call:
    inputs:
      fail-on-severity:
        type: string
        description: "Configure the severity level for vulnerability alerting. Possible values: critical, high, moderate, low."
        default: "high"
      allow-ghsas:
        type: string
        description: "A comma separated list of any GitHub Advisory IDs that can be skipped during detection. Example: 'GHSA-abcd-1234-5679, GHSA-efgh-1234-5679'"
      allow-deps:
        type: string
        description: "A comma separated list of packages to exclude from the check, specified in purl format"

permissions:
  contents: read

jobs:
  dependency-review:
    name: Scan dependencies for license compliance and vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@0c155c5e8556a497adf53f2c18edabf945ed8e70 # v4.3.2
        with:
          fail-on-severity: ${{ inputs.fail-on-severity }}
          allow-ghsas: ${{ inputs.allow-ghsas }}
          allow-dependencies-licenses: ${{ inputs.allow-deps }}
          deny-licenses: GPL-3.0, AGPL-3.0, LGPL-3.0 # these are hardcoded to be compliant with sigstore/community/LICENSING.md
